version: '3'

services:
  server:
    build: ./
    ports:
      - 4000:4000
    # depends_on:
    #   - db
    #   - elasticsearch
    environment:
      - STEAM_API_KEY
      - REDIS_URL
  redis:
    image: redis:latest
    ports:
      - "6379:6379"